issue 256: Event JSON payload with multiple events
a-ajith/ODIM pull request #32
Opened 2020-11-26 12:10 UTC by a-ajith

The PR contains the code change required for forwarding multiple events in the same event body according to the filter criteria.

2020-11-26 12:43 UTC, jeevan-kamkar requested changes
Please address the requested changes

2020-11-26 12:43 UTC, jeevan-kamkar commented on svc-events/events/publishevttosubscriber.go
> +					log.Printf("Filtered Event: %v", event)
if log. Printf is  used please add \n in the so that previous log should

2020-11-26 12:43 UTC, jeevan-kamkar commented on svc-events/events/publishevttosubscriber.go
> +func formatEvent(originResource string, event common.Event, hostIP string) (common.Event, string) {
along with OriginOfCondtion, the resource uri might be present in OEM block of the  event  that use case is  not handled

2020-11-26 12:50 UTC, shivacharanms requested changes

2020-11-26 12:50 UTC, shivacharanms commented on svc-events/events/publishevttosubscriber.go
> +			log.Println("Event not forwarded : Originofcondition is empty in incoming event", requestData)
Give space or any special character to separate the log text and the requestData

2020-11-26 12:50 UTC, shivacharanms commented on svc-events/events/publishevttosubscriber.go
> +			log.Println("Event not forwarded : Originofcondition is empty in incoming event", requestData)
Give space or any special character to separate the log text and the requestData

2020-11-26 12:50 UTC, shivacharanms commented on svc-events/events/publishevttosubscriber.go
> +			log.Println("Event not forwared: resource type of originofcondition not supported in event", message)
Give space or any special character to separate the log text and message

2020-11-30 09:29 UTC, shivacharanms approved these changes

2020-11-30 12:37 UTC, jeevan-kamkar approved these changes

2020-11-30 18:36 UTC, merged