issue-114 [task-2] Automate the proto file generation by adding the script to the Docker/Make file
a-ajith/ODIM pull request #36
Opened 2020-12-17 12:38 UTC by a-ajith

The PR contains:

1. Corrections for the RPC files generation script.
2. New script file to remove the auto-generated RPC files (files generated while development can be removed easily)
3. Makefile changes for enabling RPC file generation and removal.
> **make proto** will generate RPC files for development and testing purposes
> **make protoclean** will remove generated RPC files for clearing the repo
> _make deepclean_ will also remove the RPC files if any generated
4. Docker file changes for generating RPC files for the deployment

2020-12-17 12:44 UTC, bharath-b-hpe approved these changes

2020-12-17 13:30 UTC, jeevan-kamkar approved these changes

2020-12-18 08:06 UTC, shivacharanms approved these changes

2020-12-18 10:05 UTC, Bharath-KKB approved these changes

2020-12-18 10:49 UTC, tamanna-k approved these changes

2020-12-18 11:22 UTC, irappa-pattar approved these changes

2021-03-03 16:10 UTC, Bharath-KKB requested changes
We dont want to merge it now.

2021-04-19 08:10 UTC, Bharath-KKB approved these changes

2021-04-23 10:13 UTC, a-ajith commented
This PR is out of scope as we are moving away from GoMicro

2021-04-23 10:13 UTC, closed without merging