[Issue-499] Fix for Adding a new connection method in kube_deploy_nodes.yaml after editing and deleting it doesn't get reflected in ODIM
a-ajith/ODIM pull request #50
Opened 2021-04-07 11:00 UTC by a-ajith

The PR contains the fix for connection method update according to the config file changes.

2021-04-07 11:34 UTC, jeevan-kamkar approved these changes

2021-04-07 14:32 UTC, Bharath-KKB requested changes
Can you explain this change ?

2021-04-08 05:58 UTC, bharath-b-hpe approved these changes

2021-04-08 07:08 UTC, a-ajith commented
@Bharath-KKB updated the PR description with more details regarding the issue and the approach.

2021-04-08 10:24 UTC, Bharath-KKB approved these changes

2021-04-08 10:25 UTC, merged